### ISSUE TITLE
2차 회의록

### ISSUE THREAD

**Issue by arkss** [KoDaHyeon/introduce-#12]
# 2차 회의록

1. **회의 개요**

   |    일시    | 2018.10.8                     |
   | :--------: | ---------------------------------------------------- |
   |  **장소**  |정문 이디야 카페                          |
   | **작성일** | 2018.10.8                                            |
   | **참석자** | 강민성, 고다현, 김의중, 신원균                       |
   |  **안건**  | 1. git issue 에 대해 알아보기 <br>2. git 저장소에 조원들 초대 <br>3. ppt 내용을 md 파일로 만들기 |

2. **회의 내용**

   1. git issue 에 대해 알아보기

      * 여러 issue 를 올려보고 서로 comment 달아주기

   2. git 저장소에 조원들 초대

      * git 저장소에 조원들 초대하는 방법에 대해 알아보고 실시

   3. ppt 내용을 md 파일로 만들기
      * 강민성 : 회의록 작성
      * 고다현 : 벤치마킹
      * 김의중 : 시장조사
      * 신원균 : 방향성

| 향후일정 | 현재까지 수익을 낼 방법이 구체화 되지 않아서<br> 이 방법에 대해서 더 많은 이야기를 나눠 볼 에정 |
| :------: | ------------------------------------------------------------ |
| 특이사항 | 조원 한 명이 해외여행으로 인헤 부재하였지만 온라인으로 참석  |

**Comment by arkss** [comment]
회의 내용이 조금 부족한 듯한데 추가할 게 있을까요?

**Comment by KimEuiJoong** [comment]
과제 4 번 하는 방법 추후 교수님이방법 올려주신다는 내용 추가하면 좋을거같아요

**Comment by arkss** [comment]
그 부분 수정하겠습니다

> 과제 4 번 하는 방법 추후 교수님이방법 올려주신다는 내용 추가하면 좋을거같아요

그 부분 수정하겠습니다!
