### ISSUE TITLE
2015930006 김의중 창의공학기초설계 시장조사 목차개요

### ISSUE THREAD

**Issue by KimEuiJoong** [KoDaHyeon/introduce-#2]
1.1조별토의및마인드맵작성
구글 플레이, 앱스토어  두 마켓
1.2시장조사에 대한각 특징별 정리
인기,매출,장르 순
1.3요즘 뜨는 사회 이슈
탈모
1.4주제선정
순위권에 있는 키우기 게임 + 요즘 대중사이에 관심많은 키우기게임 = 머리카락 키우기 게임

**Comment by KoDaHyeon** [comment]
마지막 줄 오타나서 제가 수정했어요.
